version: '3'
services:
  app:
    container_name: image-store
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - "mongo"
      - "kafka"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "albumCreate:1:1,albumDelete:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"